/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_eddi;

//<editor-fold defaultstate="collapsed" desc="Imports">
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

//</editor-fold>
/**
 *
 * @author david
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        bt_Laberinto = new javax.swing.JButton();
        bt_calculo = new javax.swing.JButton();
        bt_inicio = new javax.swing.JButton();
        bt_resolucion = new javax.swing.JButton();
        bt_compresion = new javax.swing.JButton();
        bt_coloreable = new javax.swing.JButton();
        bt_origenes = new javax.swing.JButton();
        bt_origen = new javax.swing.JButton();
        bt_arbol = new javax.swing.JButton();
        panelPrincipal = new javax.swing.JPanel();
        panelInicio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelLaberinto = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelCalculo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panelResolucion = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panelCompresion = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        panelColoreable = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        panelOrigen = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        panelOrigenes = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        panelArbol = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyecto EDD1");
        setIconImage(new ImageIcon("Images/poop.png").getImage());
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(51, 54, 63));

        bt_Laberinto.setBackground(new java.awt.Color(51, 54, 63));
        bt_Laberinto.setForeground(new java.awt.Color(255, 255, 255));
        bt_Laberinto.setText("Laberinto");
        bt_Laberinto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buttonGroup1.add(bt_Laberinto);
        bt_Laberinto.setFocusable(false);
        bt_Laberinto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_LaberintoMouseClicked(evt);
            }
        });
        bt_Laberinto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_LaberintoActionPerformed(evt);
            }
        });

        bt_calculo.setBackground(new java.awt.Color(51, 54, 63));
        bt_calculo.setForeground(new java.awt.Color(255, 255, 255));
        bt_calculo.setText("<html>Calculo de Evalucion<br />  por desempeño</html>");
        bt_calculo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buttonGroup1.add(bt_calculo);
        bt_calculo.setFocusPainted(false);
        bt_calculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_calculoMouseClicked(evt);
            }
        });
        bt_calculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_calculoActionPerformed(evt);
            }
        });

        bt_inicio.setBackground(new java.awt.Color(56, 70, 101));
        bt_inicio.setForeground(new java.awt.Color(255, 255, 255));
        bt_inicio.setText("Inicio");
        bt_inicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buttonGroup1.add(bt_inicio);
        bt_inicio.setFocusable(false);
        bt_inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_inicioMouseClicked(evt);
            }
        });
        bt_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_inicioActionPerformed(evt);
            }
        });

        bt_resolucion.setBackground(new java.awt.Color(51, 54, 63));
        bt_resolucion.setForeground(new java.awt.Color(255, 255, 255));
        bt_resolucion.setText("<html>  Resolucion de<br />  problemas matematicos</html>");
        bt_resolucion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buttonGroup1.add(bt_resolucion);
        bt_resolucion.setFocusPainted(false);
        bt_resolucion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_resolucionMouseClicked(evt);
            }
        });
        bt_resolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_resolucionActionPerformed(evt);
            }
        });

        bt_compresion.setBackground(new java.awt.Color(51, 54, 63));
        bt_compresion.setForeground(new java.awt.Color(255, 255, 255));
        bt_compresion.setText("<html>Compresion de<br />  archivo de texto</html>");
        bt_compresion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buttonGroup1.add(bt_compresion);
        bt_compresion.setFocusPainted(false);
        bt_compresion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_compresionMouseClicked(evt);
            }
        });
        bt_compresion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_compresionActionPerformed(evt);
            }
        });

        bt_coloreable.setBackground(new java.awt.Color(51, 54, 63));
        bt_coloreable.setForeground(new java.awt.Color(255, 255, 255));
        bt_coloreable.setText("bi-coloreable");
        bt_coloreable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buttonGroup1.add(bt_coloreable);
        bt_coloreable.setFocusPainted(false);
        bt_coloreable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_coloreableMouseClicked(evt);
            }
        });
        bt_coloreable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_coloreableActionPerformed(evt);
            }
        });

        bt_origenes.setBackground(new java.awt.Color(51, 54, 63));
        bt_origenes.setForeground(new java.awt.Color(255, 255, 255));
        bt_origenes.setText("Origenes/destinos");
        bt_origenes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buttonGroup1.add(bt_origenes);
        bt_origenes.setFocusPainted(false);
        bt_origenes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_origenesMouseClicked(evt);
            }
        });
        bt_origenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_origenesActionPerformed(evt);
            }
        });

        bt_origen.setBackground(new java.awt.Color(51, 54, 63));
        bt_origen.setForeground(new java.awt.Color(255, 255, 255));
        bt_origen.setText("Origen/destinos");
        bt_origen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buttonGroup1.add(bt_origen);
        bt_origen.setFocusPainted(false);
        bt_origen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_origenMouseClicked(evt);
            }
        });
        bt_origen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_origenActionPerformed(evt);
            }
        });

        bt_arbol.setBackground(new java.awt.Color(51, 54, 63));
        bt_arbol.setForeground(new java.awt.Color(255, 255, 255));
        bt_arbol.setText("Arbol");
        bt_arbol.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buttonGroup1.add(bt_arbol);
        bt_arbol.setFocusPainted(false);
        bt_arbol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_arbolMouseClicked(evt);
            }
        });
        bt_arbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_arbolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bt_Laberinto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bt_calculo)
            .addComponent(bt_inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bt_resolucion, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
            .addComponent(bt_compresion)
            .addComponent(bt_coloreable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bt_origenes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bt_origen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bt_arbol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(bt_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bt_Laberinto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bt_calculo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bt_resolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bt_compresion, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bt_coloreable, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bt_origenes, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bt_origen, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bt_arbol, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        panelPrincipal.setName("panelPrincipal"); // NOI18N
        panelPrincipal.setLayout(new java.awt.CardLayout());

        panelInicio.setName("panelInicio"); // NOI18N

        jLabel1.setText("Inicio, obvio estos labels se borraran. Solo son con fines didacticos");

        javax.swing.GroupLayout panelInicioLayout = new javax.swing.GroupLayout(panelInicio);
        panelInicio.setLayout(panelInicioLayout);
        panelInicioLayout.setHorizontalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicioLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel1))
        );
        panelInicioLayout.setVerticalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicioLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel1))
        );

        panelPrincipal.add(panelInicio, "panelInicio");

        panelLaberinto.setName("panelLaberinto"); // NOI18N

        jLabel2.setText("Esto es el laberinto");

        javax.swing.GroupLayout panelLaberintoLayout = new javax.swing.GroupLayout(panelLaberinto);
        panelLaberinto.setLayout(panelLaberintoLayout);
        panelLaberintoLayout.setHorizontalGroup(
            panelLaberintoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLaberintoLayout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(jLabel2)
                .addContainerGap(431, Short.MAX_VALUE))
        );
        panelLaberintoLayout.setVerticalGroup(
            panelLaberintoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLaberintoLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel2)
                .addContainerGap(396, Short.MAX_VALUE))
        );

        panelPrincipal.add(panelLaberinto, "panelLaberinto");
        panelLaberinto.getAccessibleContext().setAccessibleName("");

        jLabel3.setText("Calculo de evaluacion");

        javax.swing.GroupLayout panelCalculoLayout = new javax.swing.GroupLayout(panelCalculo);
        panelCalculo.setLayout(panelCalculoLayout);
        panelCalculoLayout.setHorizontalGroup(
            panelCalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCalculoLayout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jLabel3)
                .addContainerGap(411, Short.MAX_VALUE))
        );
        panelCalculoLayout.setVerticalGroup(
            panelCalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCalculoLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jLabel3)
                .addContainerGap(404, Short.MAX_VALUE))
        );

        panelPrincipal.add(panelCalculo, "panelCalculo");

        jLabel4.setText("Resolucion de problemas mat.");

        javax.swing.GroupLayout panelResolucionLayout = new javax.swing.GroupLayout(panelResolucion);
        panelResolucion.setLayout(panelResolucionLayout);
        panelResolucionLayout.setHorizontalGroup(
            panelResolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResolucionLayout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addComponent(jLabel4)
                .addContainerGap(316, Short.MAX_VALUE))
        );
        panelResolucionLayout.setVerticalGroup(
            panelResolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResolucionLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel4)
                .addContainerGap(408, Short.MAX_VALUE))
        );

        panelPrincipal.add(panelResolucion, "panelResolucion");

        jLabel5.setText("Compresion de archivos");

        javax.swing.GroupLayout panelCompresionLayout = new javax.swing.GroupLayout(panelCompresion);
        panelCompresion.setLayout(panelCompresionLayout);
        panelCompresionLayout.setHorizontalGroup(
            panelCompresionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCompresionLayout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(jLabel5)
                .addContainerGap(338, Short.MAX_VALUE))
        );
        panelCompresionLayout.setVerticalGroup(
            panelCompresionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCompresionLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel5)
                .addContainerGap(418, Short.MAX_VALUE))
        );

        panelPrincipal.add(panelCompresion, "panelCompresion");

        jLabel6.setText("Coloreable");

        javax.swing.GroupLayout panelColoreableLayout = new javax.swing.GroupLayout(panelColoreable);
        panelColoreable.setLayout(panelColoreableLayout);
        panelColoreableLayout.setHorizontalGroup(
            panelColoreableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelColoreableLayout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(jLabel6)
                .addContainerGap(411, Short.MAX_VALUE))
        );
        panelColoreableLayout.setVerticalGroup(
            panelColoreableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelColoreableLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel6)
                .addContainerGap(422, Short.MAX_VALUE))
        );

        panelPrincipal.add(panelColoreable, "panelColoreable");

        jLabel7.setText("Origen");

        javax.swing.GroupLayout panelOrigenLayout = new javax.swing.GroupLayout(panelOrigen);
        panelOrigen.setLayout(panelOrigenLayout);
        panelOrigenLayout.setHorizontalGroup(
            panelOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOrigenLayout.createSequentialGroup()
                .addGap(297, 297, 297)
                .addComponent(jLabel7)
                .addContainerGap(453, Short.MAX_VALUE))
        );
        panelOrigenLayout.setVerticalGroup(
            panelOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOrigenLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel7)
                .addContainerGap(394, Short.MAX_VALUE))
        );

        panelPrincipal.add(panelOrigen, "panelOrigen");

        jLabel8.setText("Origenes");

        javax.swing.GroupLayout panelOrigenesLayout = new javax.swing.GroupLayout(panelOrigenes);
        panelOrigenes.setLayout(panelOrigenesLayout);
        panelOrigenesLayout.setHorizontalGroup(
            panelOrigenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOrigenesLayout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addComponent(jLabel8)
                .addContainerGap(448, Short.MAX_VALUE))
        );
        panelOrigenesLayout.setVerticalGroup(
            panelOrigenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOrigenesLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel8)
                .addContainerGap(399, Short.MAX_VALUE))
        );

        panelPrincipal.add(panelOrigenes, "panelOrigenes");

        jLabel9.setText("Arbol");

        javax.swing.GroupLayout panelArbolLayout = new javax.swing.GroupLayout(panelArbol);
        panelArbol.setLayout(panelArbolLayout);
        panelArbolLayout.setHorizontalGroup(
            panelArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelArbolLayout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addComponent(jLabel9)
                .addContainerGap(473, Short.MAX_VALUE))
        );
        panelArbolLayout.setVerticalGroup(
            panelArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelArbolLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel9)
                .addContainerGap(406, Short.MAX_VALUE))
        );

        panelPrincipal.add(panelArbol, "panelArbol");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_LaberintoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_LaberintoMouseClicked
        // TODO add your handling code here:
        buttonGroup1.setSelected(bt_Laberinto.getModel(), true);
        if (buttonGroup1.isSelected(bt_Laberinto.getModel())) {
            bt_calculo.setBackground(new Color(51, 54, 63));
            bt_inicio.setBackground(new Color(51, 54, 63));
            bt_resolucion.setBackground(new Color(51, 54, 63));
            bt_compresion.setBackground(new Color(51, 54, 63));
            bt_coloreable.setBackground(new Color(51, 54, 63));
            bt_origenes.setBackground(new Color(51, 53, 63));
            bt_origen.setBackground(new Color(51, 54, 63));
            bt_arbol.setBackground(new Color(51, 54, 63));
            bt_Laberinto.setBackground(new Color(56, 70, 101));
        }
    }//GEN-LAST:event_bt_LaberintoMouseClicked

    private void bt_calculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_calculoMouseClicked
        // TODO add your handling code here:
        buttonGroup1.setSelected(bt_calculo.getModel(), true);
        if (buttonGroup1.isSelected(bt_calculo.getModel())) {
            bt_Laberinto.setBackground(new Color(51, 54, 63));
            bt_inicio.setBackground(new Color(51, 54, 63));
            bt_resolucion.setBackground(new Color(51, 54, 63));
            bt_compresion.setBackground(new Color(51, 54, 63));
            bt_coloreable.setBackground(new Color(51, 54, 63));
            bt_origenes.setBackground(new Color(51, 53, 63));
            bt_origen.setBackground(new Color(51, 54, 63));
            bt_arbol.setBackground(new Color(51, 54, 63));
            bt_calculo.setBackground(new Color(56, 70, 101));
        }
    }//GEN-LAST:event_bt_calculoMouseClicked

    private void bt_inicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_inicioMouseClicked
        // TODO add your handling code here:
        buttonGroup1.setSelected(bt_inicio.getModel(), true);
        if (buttonGroup1.isSelected(bt_inicio.getModel())) {
            bt_Laberinto.setBackground(new Color(51, 54, 63));
            bt_calculo.setBackground(new Color(51, 54, 63));
            bt_resolucion.setBackground(new Color(51, 54, 63));
            bt_compresion.setBackground(new Color(51, 54, 63));
            bt_coloreable.setBackground(new Color(51, 54, 63));
            bt_origenes.setBackground(new Color(51, 53, 63));
            bt_origen.setBackground(new Color(51, 54, 63));
            bt_arbol.setBackground(new Color(51, 54, 63));
            bt_inicio.setBackground(new Color(56, 70, 101));
        }
    }//GEN-LAST:event_bt_inicioMouseClicked

    private void bt_resolucionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_resolucionMouseClicked
        // TODO add your handling code here:
        buttonGroup1.setSelected(bt_resolucion.getModel(), true);
        if (buttonGroup1.isSelected(bt_resolucion.getModel())) {
            bt_Laberinto.setBackground(new Color(51, 54, 63));
            bt_calculo.setBackground(new Color(51, 54, 63));
            bt_inicio.setBackground(new Color(51, 54, 63));
            bt_compresion.setBackground(new Color(51, 54, 63));
            bt_coloreable.setBackground(new Color(51, 54, 63));
            bt_origenes.setBackground(new Color(51, 53, 63));
            bt_origen.setBackground(new Color(51, 54, 63));
            bt_arbol.setBackground(new Color(51, 54, 63));
            bt_resolucion.setBackground(new Color(56, 70, 101));
        }
    }//GEN-LAST:event_bt_resolucionMouseClicked

    private void bt_compresionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_compresionMouseClicked
        // TODO add your handling code here:
        buttonGroup1.setSelected(bt_compresion.getModel(), true);
        if (buttonGroup1.isSelected(bt_compresion.getModel())) {
            bt_Laberinto.setBackground(new Color(51, 54, 63));
            bt_calculo.setBackground(new Color(51, 54, 63));
            bt_inicio.setBackground(new Color(51, 54, 63));
            bt_resolucion.setBackground(new Color(51, 54, 63));
            bt_coloreable.setBackground(new Color(51, 54, 63));
            bt_origenes.setBackground(new Color(51, 53, 63));
            bt_origen.setBackground(new Color(51, 54, 63));
            bt_arbol.setBackground(new Color(51, 54, 63));
            bt_compresion.setBackground(new Color(56, 70, 101));
        }
    }//GEN-LAST:event_bt_compresionMouseClicked

    private void bt_coloreableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_coloreableMouseClicked
        // TODO add your handling code here:
        buttonGroup1.setSelected(bt_coloreable.getModel(), true);
        if (buttonGroup1.isSelected(bt_coloreable.getModel())) {
            bt_Laberinto.setBackground(new Color(51, 54, 63));
            bt_calculo.setBackground(new Color(51, 54, 63));
            bt_inicio.setBackground(new Color(51, 54, 63));
            bt_resolucion.setBackground(new Color(51, 54, 63));
            bt_compresion.setBackground(new Color(51, 54, 63));
            bt_origenes.setBackground(new Color(51, 53, 63));
            bt_origen.setBackground(new Color(51, 54, 63));
            bt_arbol.setBackground(new Color(51, 54, 63));
            bt_coloreable.setBackground(new Color(56, 70, 101));
        }
    }//GEN-LAST:event_bt_coloreableMouseClicked

    private void bt_origenesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_origenesMouseClicked
        // TODO add your handling code here:
        buttonGroup1.setSelected(bt_origenes.getModel(), true);
        if (buttonGroup1.isSelected(bt_origenes.getModel())) {
            bt_Laberinto.setBackground(new Color(51, 54, 63));
            bt_calculo.setBackground(new Color(51, 54, 63));
            bt_inicio.setBackground(new Color(51, 54, 63));
            bt_resolucion.setBackground(new Color(51, 54, 63));
            bt_compresion.setBackground(new Color(51, 54, 63));
            bt_coloreable.setBackground(new Color(51, 54, 63));
            bt_origen.setBackground(new Color(51, 54, 63));
            bt_arbol.setBackground(new Color(51, 54, 63));
            bt_origenes.setBackground(new Color(56, 70, 101));
        }
    }//GEN-LAST:event_bt_origenesMouseClicked

    private void bt_origenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_origenMouseClicked
        // TODO add your handling code here:
        buttonGroup1.setSelected(bt_origen.getModel(), true);
        if (buttonGroup1.isSelected(bt_origen.getModel())) {
            bt_Laberinto.setBackground(new Color(51, 54, 63));
            bt_calculo.setBackground(new Color(51, 54, 63));
            bt_inicio.setBackground(new Color(51, 54, 63));
            bt_resolucion.setBackground(new Color(51, 54, 63));
            bt_compresion.setBackground(new Color(51, 54, 63));
            bt_coloreable.setBackground(new Color(51, 54, 63));
            bt_origenes.setBackground(new Color(51, 53, 63));
            bt_arbol.setBackground(new Color(51, 54, 63));
            bt_origen.setBackground(new Color(56, 70, 101));
        }
    }//GEN-LAST:event_bt_origenMouseClicked

    private void bt_arbolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_arbolMouseClicked
        // TODO add your handling code here:
        buttonGroup1.setSelected(bt_arbol.getModel(), true);
        if (buttonGroup1.isSelected(bt_arbol.getModel())) {
            bt_Laberinto.setBackground(new Color(51, 54, 63));
            bt_calculo.setBackground(new Color(51, 54, 63));
            bt_inicio.setBackground(new Color(51, 54, 63));
            bt_resolucion.setBackground(new Color(51, 54, 63));
            bt_compresion.setBackground(new Color(51, 54, 63));
            bt_coloreable.setBackground(new Color(51, 54, 63));
            bt_origenes.setBackground(new Color(51, 53, 63));
            bt_origen.setBackground(new Color(51, 53, 63));
            bt_arbol.setBackground(new Color(56, 70, 101));
        }
    }//GEN-LAST:event_bt_arbolMouseClicked

    private void bt_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_inicioActionPerformed
        card = (CardLayout)panelPrincipal.getLayout();
        card.show(panelPrincipal,"panelInicio");
    }//GEN-LAST:event_bt_inicioActionPerformed

    private void bt_LaberintoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_LaberintoActionPerformed
        card = (CardLayout)panelPrincipal.getLayout();
        card.show(panelPrincipal,"panelLaberinto");
    }//GEN-LAST:event_bt_LaberintoActionPerformed

    private void bt_calculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_calculoActionPerformed
        card = (CardLayout)panelPrincipal.getLayout();
        card.show(panelPrincipal,"panelCalculo");
    }//GEN-LAST:event_bt_calculoActionPerformed

    private void bt_resolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_resolucionActionPerformed
        card = (CardLayout)panelPrincipal.getLayout();
        card.show(panelPrincipal,"panelResolucion");
    }//GEN-LAST:event_bt_resolucionActionPerformed

    private void bt_compresionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_compresionActionPerformed
        card = (CardLayout)panelPrincipal.getLayout();
        card.show(panelPrincipal,"panelCompresion");
    }//GEN-LAST:event_bt_compresionActionPerformed

    private void bt_coloreableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_coloreableActionPerformed
        card = (CardLayout)panelPrincipal.getLayout();
        card.show(panelPrincipal,"panelColoreable");
    }//GEN-LAST:event_bt_coloreableActionPerformed

    private void bt_origenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_origenesActionPerformed
        card = (CardLayout)panelPrincipal.getLayout();
        card.show(panelPrincipal,"panelOrigenes");
    }//GEN-LAST:event_bt_origenesActionPerformed

    private void bt_origenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_origenActionPerformed
        card = (CardLayout)panelPrincipal.getLayout();
        card.show(panelPrincipal,"panelOrigen");
    }//GEN-LAST:event_bt_origenActionPerformed

    private void bt_arbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_arbolActionPerformed
        card = (CardLayout)panelPrincipal.getLayout();
        card.show(panelPrincipal,"panelArbol");
    }//GEN-LAST:event_bt_arbolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
//<editor-fold defaultstate="collapsed" desc="Variables">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Laberinto;
    private javax.swing.JButton bt_arbol;
    private javax.swing.JButton bt_calculo;
    private javax.swing.JButton bt_coloreable;
    private javax.swing.JButton bt_compresion;
    private javax.swing.JButton bt_inicio;
    private javax.swing.JButton bt_origen;
    private javax.swing.JButton bt_origenes;
    private javax.swing.JButton bt_resolucion;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelArbol;
    private javax.swing.JPanel panelCalculo;
    private javax.swing.JPanel panelColoreable;
    private javax.swing.JPanel panelCompresion;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JPanel panelLaberinto;
    private javax.swing.JPanel panelOrigen;
    private javax.swing.JPanel panelOrigenes;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelResolucion;
    // End of variables declaration//GEN-END:variables
//</editor-fold>
    private CardLayout card = new CardLayout();
}
